pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - status-success=build (macos-latest, 10)
      - status-success=build (macos-latest, 12)
      - status-success=build (windows-latest, 10)
      - status-success=build (windows-latest, 12)
      - status-success=build (ubuntu-latest, 10)
      - status-success=build (ubuntu-latest, 12)
    actions:
      merge:
        method: squash
